# Generated by Django 4.2.7 on 2025-12-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shartnoma', 'verbose_name_plural': 'Shartnomalar'},
        ),
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={'ordering': ['name'], 'verbose_name': 'Shartnoma shabloni', 'verbose_name_plural': 'Shartnoma shablonlari'},
        ),
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['due_date'], 'verbose_name': 'Qarz', 'verbose_name_plural': 'Qarzlar'},
        ),
        migrations.AlterModelOptions(
            name='financialreport',
            options={'ordering': ['-period_end', '-period_start'], 'verbose_name': 'Moliya hisoboti', 'verbose_name_plural': 'Moliya hisobotlari'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['-created_at'], 'verbose_name': "To'lov tarixi", 'verbose_name_plural': "To'lovlar tarixi"},
        ),
        migrations.AlterModelOptions(
            name='paymentplan',
            options={'ordering': ['contract', 'installment_number'], 'verbose_name': "To'lov rejasi", 'verbose_name_plural': "To'lov rejalari"},
        ),
        migrations.AlterModelOptions(
            name='paymentreminder',
            options={'ordering': ['reminder_date', 'priority'], 'verbose_name': "To'lov eslatmasi", 'verbose_name_plural': "To'lov eslatmalari"},
        ),
    ]
