# Generated by Django 4.2.7 on 2025-12-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_branch_options_alter_parentprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='parent_telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Ota-ona Telegram ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Menejer'), ('mentor', 'Mentor'), ('student', "O'quvchi"), ('accountant', 'Buxgalter'), ('sales', 'Sotuvchi'), ('sales_manager', 'Sotuvchilar menejeri')], default='student', max_length=20, verbose_name='Rol'),
        ),
        migrations.DeleteModel(
            name='ParentProfile',
        ),
    ]
