# Generated by Django 5.0.1 on 2025-12-13 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_courses_cou_is_acti_63c274_idx_and_more'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['date', 'is_active'], name='exams_exam_date_adbaa1_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course', 'date'], name='exams_exam_course__c20d68_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['group', 'date'], name='exams_exam_group_i_b0618b_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student', 'exam'], name='exams_examr_student_52c208_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['score', 'is_passed'], name='exams_examr_score_4c85a1_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['submitted_at'], name='exams_examr_submitt_4c8d3a_idx'),
        ),
    ]
