# Generated by Django 4.2.7 on 2025-12-15 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_course_courses_cou_is_acti_63c274_idx_and_more'),
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_dashboard', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Dashboard',
                'verbose_name_plural': 'Parent Dashboards',
                'unique_together': {('parent', 'student')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyParentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('attendance_percentage', models.FloatField(default=0.0)),
                ('present_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('absent_count', models.IntegerField(default=0)),
                ('total_lessons', models.IntegerField(default=0)),
                ('total_homeworks', models.IntegerField(default=0)),
                ('completed_homeworks', models.IntegerField(default=0)),
                ('on_time_homeworks', models.IntegerField(default=0)),
                ('late_homeworks', models.IntegerField(default=0)),
                ('homework_completion_rate', models.FloatField(default=0.0)),
                ('total_exams', models.IntegerField(default=0)),
                ('passed_exams', models.IntegerField(default=0)),
                ('average_exam_score', models.FloatField(default=0.0)),
                ('best_exam_score', models.FloatField(default=0.0)),
                ('worst_exam_score', models.FloatField(default=0.0)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('weaknesses', models.TextField(blank=True, null=True)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('previous_month_progress', models.FloatField(default=0.0)),
                ('progress_change', models.CharField(blank=True, choices=[('improved', 'Yaxshilandi'), ('stable', 'Barqaror'), ('declined', 'Pasaydi')], max_length=20, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_monthly_reports', to='courses.group')),
                ('mentor_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_reports', to='mentors.monthlyreport')),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_monthly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Parent Report',
                'verbose_name_plural': 'Monthly Parent Reports',
                'ordering': ['-year', '-month', '-created_at'],
                'indexes': [models.Index(fields=['parent', 'year', 'month'], name='parents_mon_parent__f2b274_idx'), models.Index(fields=['student', 'year', 'month'], name='parents_mon_student_df7709_idx'), models.Index(fields=['group', 'year', 'month'], name='parents_mon_group_i_f056ea_idx')],
                'unique_together': {('parent', 'student', 'group', 'month', 'year')},
            },
        ),
    ]
