"""
Django settings for geeks_crm project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-c^92fw&(ph@-x&hrdchqb(o!1al&hi+3729aj*o^8bfq#rs)5n')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    # 'django_extensions',  # Optional - comment qilindi
    'corsheaders',
    
    # Local apps
    'accounts',
    'courses',
    'attendance',
    'homework',
    'exams',
    'gamification',
    'mentors',
    'parents',
    'crm',
    'finance',
    'telegram_bot',
    'analytics',
    'schedule',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'geeks_crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'geeks_crm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Custom User Model
AUTH_USER_MODEL = 'accounts.User'


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login/Logout URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Celery Configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Celery Beat Schedule (optional - can be configured in celery.py)
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'send-lesson-reminders': {
        'task': 'telegram_bot.tasks.send_lesson_reminder',
        'schedule': crontab(minute='*/5'),  # Har 5 daqiqada
    },
    'send-homework-deadline-reminders': {
        'task': 'telegram_bot.tasks.send_homework_deadline_reminder',
        'schedule': crontab(hour=9, minute=0),  # Har kuni soat 9:00
    },
    'send-attendance-notifications': {
        'task': 'telegram_bot.tasks.send_attendance_notification_to_parents',
        'schedule': crontab(hour=20, minute=0),  # Har kuni soat 20:00
    },
    # Gamification rankings
    'update-group-rankings': {
        'task': 'gamification.tasks.update_group_rankings',
        'schedule': crontab(hour='*/2', minute=0),  # Har 2 soatda
    },
    'update-branch-rankings': {
        'task': 'gamification.tasks.update_branch_rankings',
        'schedule': crontab(hour='*/4', minute=0),  # Har 4 soatda
    },
    'update-overall-rankings': {
        'task': 'gamification.tasks.update_overall_rankings',
        'schedule': crontab(hour='*/6', minute=0),  # Har 6 soatda
    },
    'update-monthly-rankings': {
        'task': 'gamification.tasks.update_monthly_rankings',
        'schedule': crontab(day_of_month=1, hour=0, minute=0),  # Har oy 1-kuni
    },
    # Mentor KPI
    'calculate-all-mentors-kpi': {
        'task': 'mentors.tasks.calculate_all_mentors_kpi',
        'schedule': crontab(day_of_month=1, hour=2, minute=0),  # Har oy 1-kuni soat 2:00
    },
    'update-mentor-rankings': {
        'task': 'mentors.tasks.update_mentor_rankings',
        'schedule': crontab(day_of_month=1, hour=3, minute=0),  # Har oy 1-kuni soat 3:00
    },
    # Parents monthly reports
    'generate-monthly-parent-reports': {
        'task': 'parents.tasks.generate_monthly_parent_reports',
        'schedule': crontab(day_of_month=1, hour=4, minute=0),  # Har oy 1-kuni soat 4:00
    },
    # CRM tasks
    'assign-leads-to-sales': {
        'task': 'crm.tasks.assign_leads_to_sales',
        'schedule': crontab(minute='*/10'),  # Har 10 daqiqada
    },
    'check-overdue-followups': {
        'task': 'crm.tasks.check_overdue_followups',
        'schedule': crontab(minute='*/5'),  # Har 5 daqiqada
    },
    'create-contacted-followups': {
        'task': 'crm.tasks.create_contacted_followups',
        'schedule': crontab(hour='*/2', minute=0),  # Har 2 soatda
    },
    'reactivate-lost-leads': {
        'task': 'crm.tasks.reactivate_lost_leads',
        'schedule': crontab(hour=8, minute=0),  # Har kuni soat 8:00
    },
    'calculate-sales-kpi': {
        'task': 'crm.tasks.calculate_sales_kpi',
        'schedule': crontab(day_of_month=1, hour=5, minute=0),  # Har oy 1-kuni soat 5:00
    },
    'check-leave-expiry': {
        'task': 'crm.tasks.check_leave_expiry',
        'schedule': crontab(hour=0, minute=0),  # Har kuni yarim tun
    },
    'send-followup-reminders': {
        'task': 'crm.tasks.send_followup_reminders',
        'schedule': crontab(minute='*/30'),  # Har 30 daqiqada
    },
    'send-trial-reminders': {
        'task': 'crm.tasks.send_trial_reminders',
        'schedule': crontab(minute='*/15'),  # Har 15 daqiqada
    },
    'check-reactivation': {
        'task': 'crm.tasks.check_reactivation',
        'schedule': crontab(hour=9, minute=0),  # Har kuni soat 9:00
    },
    'calculate-daily-kpi': {
        'task': 'crm.tasks.calculate_daily_kpi',
        'schedule': crontab(hour=23, minute=55),  # Har kuni soat 23:55
    },
    'send-daily-statistics': {
        'task': 'crm.tasks.send_daily_statistics',
        'schedule': crontab(hour=20, minute=0),  # Har kuni soat 20:00
    },
    'import-google-sheets': {
        'task': 'crm.tasks.import_leads_from_google_sheets',
        'schedule': crontab(minute='*/30'),  # Har 30 daqiqada
    },
    # Finance tasks
    'create-payment-reminders': {
        'task': 'finance.tasks.create_payment_reminders',
        'schedule': crontab(hour=9, minute=0),  # Har kuni soat 9:00
    },
    'check-overdue-payments': {
        'task': 'finance.tasks.check_overdue_payments',
        'schedule': crontab(hour=10, minute=0),  # Har kuni soat 10:00
    },
    'generate-monthly-financial-report': {
        'task': 'finance.tasks.generate_monthly_financial_report',
        'schedule': crontab(day_of_month=1, hour=6, minute=0),  # Har oy 1-kuni soat 6:00
    },
}

# Redis Cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': config('REDIS_URL', default='redis://localhost:6379/1'),
    }
}

# Telegram Bot Configuration
TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')

# Google Sheets Configuration
GOOGLE_SHEETS_CREDENTIALS = config('GOOGLE_SHEETS_CREDENTIALS', default='')
GOOGLE_SHEETS_ID = config('GOOGLE_SHEETS_ID', default='')

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Session Configuration
SESSION_COOKIE_AGE = 86400  # 1 day
SESSION_SAVE_EVERY_REQUEST = True
