# Generated by Django 4.2.7 on 2025-12-15 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_course_courses_cou_is_acti_63c274_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('positive', 'Ijobiy'), ('negative', 'Salbiy'), ('neutral', 'Neytral'), ('suggestion', 'Taklif')], default='neutral', max_length=20)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Feedback',
                'verbose_name_plural': 'Parent Feedbacks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mentor', 'created_at'], name='mentors_par_mentor__4f22f9_idx'), models.Index(fields=['parent', 'created_at'], name='mentors_par_parent__765980_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('character', models.CharField(blank=True, choices=[('excellent', "A'lo"), ('good', 'Yaxshi'), ('satisfactory', 'Qoniqarli'), ('needs_improvement', 'Yaxshilash kerak')], max_length=20, null=True)),
                ('attendance', models.CharField(blank=True, choices=[('excellent', "A'lo (95-100%)"), ('good', 'Yaxshi (85-94%)'), ('satisfactory', 'Qoniqarli (70-84%)'), ('poor', 'Qoniqarsiz (<70%)')], max_length=20, null=True)),
                ('mastery', models.CharField(blank=True, choices=[('excellent', "A'lo"), ('good', 'Yaxshi'), ('satisfactory', 'Qoniqarli'), ('needs_improvement', 'Yaxshilash kerak')], max_length=20, null=True)),
                ('progress_change', models.CharField(blank=True, choices=[('improved', 'Yaxshilandi'), ('stable', 'Barqaror'), ('declined', 'Pasaydi')], max_length=20, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='courses.group')),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_monthly_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_monthly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Report',
                'verbose_name_plural': 'Monthly Reports',
                'ordering': ['-year', '-month', '-created_at'],
                'indexes': [models.Index(fields=['mentor', 'year', 'month'], name='mentors_mon_mentor__bfabc3_idx'), models.Index(fields=['student', 'year', 'month'], name='mentors_mon_student_4af4b6_idx'), models.Index(fields=['group', 'year', 'month'], name='mentors_mon_group_i_85d7bb_idx')],
                'unique_together': {('mentor', 'student', 'group', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MentorRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('total_kpi_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor Ranking',
                'verbose_name_plural': 'Mentor Rankings',
                'ordering': ['-year', '-month', 'rank'],
                'indexes': [models.Index(fields=['year', 'month', 'rank'], name='mentors_men_year_8c9262_idx'), models.Index(fields=['mentor', 'year', 'month'], name='mentors_men_mentor__f18a7a_idx')],
                'unique_together': {('mentor', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MentorKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('lesson_quality_score', models.FloatField(default=0.0)),
                ('attendance_entry_score', models.FloatField(default=0.0)),
                ('homework_grading_score', models.FloatField(default=0.0)),
                ('student_progress_score', models.FloatField(default=0.0)),
                ('group_rating_score', models.FloatField(default=0.0)),
                ('parent_feedback_score', models.FloatField(default=0.0)),
                ('monthly_report_score', models.FloatField(default=0.0)),
                ('total_kpi_score', models.FloatField(default=0.0)),
                ('total_lessons', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('completed_reports', models.IntegerField(default=0)),
                ('total_reports', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor KPI',
                'verbose_name_plural': 'Mentor KPIs',
                'ordering': ['-year', '-month', '-total_kpi_score'],
                'indexes': [models.Index(fields=['mentor', 'year', 'month'], name='mentors_men_mentor__aac0c5_idx'), models.Index(fields=['total_kpi_score', 'year', 'month'], name='mentors_men_total_k_1c53e7_idx')],
                'unique_together': {('mentor', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LessonQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_ratings', to='courses.lesson')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Quality',
                'verbose_name_plural': 'Lesson Qualities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lesson', 'rating'], name='mentors_les_lesson__f18de2_idx'), models.Index(fields=['student', 'created_at'], name='mentors_les_student_381af0_idx')],
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
