# Generated by Django 5.0.1 on 2025-12-13 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_accounts_us_role_2b136f_idx_and_more'),
        ('courses', '0002_studentprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active', 'branch'], name='courses_cou_is_acti_63c274_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='courses_cou_created_51cadc_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['date', 'start_time'], name='courses_les_date_f62ead_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group', 'date'], name='courses_les_group_i_c99ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['mentor', 'date'], name='courses_les_mentor__af9667_idx'),
        ),
    ]
