# Generated by Django 4.2.7 on 2025-12-15 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_course_courses_cou_is_acti_63c274_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Group Transfer',
                'verbose_name_plural': 'Group Transfers',
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='studentprogress',
            options={'ordering': ['-progress_percentage'], 'verbose_name': 'Student Progress', 'verbose_name_plural': 'Student Progresses'},
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_created_51cadc_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='courses_les_mentor__af9667_idx',
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_lessons',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='homework_description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='enrolled_at',
        ),
        migrations.RemoveField(
            model_name='topicmaterial',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='topicmaterial',
            name='video_url',
        ),
        migrations.AddField(
            model_name='course',
            name='duration_weeks',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='room',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='duration_minutes',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='topicmaterial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicmaterial',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topicmaterial',
            name='material_type',
            field=models.CharField(choices=[('video', 'Video'), ('file', 'Fayl'), ('link', 'Link'), ('text', 'Matn')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='grouptransfer',
            name='from_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='courses.group'),
        ),
        migrations.AddField(
            model_name='grouptransfer',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='group_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouptransfer',
            name='to_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='courses.group'),
        ),
        migrations.AddField(
            model_name='grouptransfer',
            name='transferred_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='grouptransfer',
            index=models.Index(fields=['student', 'transferred_at'], name='courses_gro_student_2ff009_idx'),
        ),
        migrations.AddIndex(
            model_name='grouptransfer',
            index=models.Index(fields=['from_group', 'to_group'], name='courses_gro_from_gr_673ffb_idx'),
        ),
    ]
