# Generated by Django 4.2.7 on 2025-12-18 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_grouptransfer_alter_studentprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['course', 'name'], 'verbose_name': 'Guruh', 'verbose_name_plural': 'Guruhlar'},
        ),
        migrations.AlterModelOptions(
            name='grouptransfer',
            options={'ordering': ['-transferred_at'], 'verbose_name': "Guruh o'tkazish", 'verbose_name_plural': "Guruh o'tkazishlar"},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-date', '-start_time'], 'verbose_name': 'Dars', 'verbose_name_plural': 'Darslar'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['course', 'order'], 'verbose_name': 'Modul', 'verbose_name_plural': 'Modullar'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['branch', 'name'], 'verbose_name': 'Xona', 'verbose_name_plural': 'Xonalar'},
        ),
        migrations.AlterModelOptions(
            name='studentprogress',
            options={'ordering': ['-progress_percentage'], 'verbose_name': "O'quvchi progressi", 'verbose_name_plural': "O'quvchi progresslari"},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['module', 'order'], 'verbose_name': 'Mavzu', 'verbose_name_plural': 'Mavzular'},
        ),
        migrations.AlterModelOptions(
            name='topicmaterial',
            options={'ordering': ['topic', 'order'], 'verbose_name': 'Mavzu materiali', 'verbose_name_plural': 'Mavzu materiallari'},
        ),
    ]
