# Generated by Django 4.2.7 on 2025-12-27 06:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
