# Generated by Django 5.0.1 on 2025-12-13 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_courses_cou_is_acti_63c274_idx_and_more'),
        ('homework', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['student', 'deadline'], name='homework_ho_student_ade818_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['is_submitted', 'deadline'], name='homework_ho_is_subm_9fe8a2_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['lesson', 'student'], name='homework_ho_lesson__e4ef39_idx'),
        ),
    ]
