# Generated by Django 4.2.7 on 2025-12-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_homework_homework_ho_student_ade818_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='description',
        ),
        migrations.AddField(
            model_name='homework',
            name='assignment_description',
            field=models.TextField(blank=True, null=True, verbose_name='Vazifa tavsifi'),
        ),
        migrations.AddField(
            model_name='homework',
            name='student_response',
            field=models.TextField(blank=True, null=True, verbose_name="O'quvchi javobi"),
        ),
    ]
