# Generated by Django 4.2.7 on 2025-12-15 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_course_courses_cou_is_acti_63c274_idx_and_more'),
        ('accounts', '0002_user_accounts_us_role_2b136f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(choices=[('new', 'Yangi'), ('contacted', 'Aloqa qilindi'), ('interested', 'Qiziqmoqda'), ('trial_registered', 'Sinovga yozildi'), ('trial_attended', 'Sinovga keldi'), ('trial_not_attended', 'Sinovga kelmadi'), ('offer_sent', 'Sotuv taklifi'), ('enrolled', 'Kursga yozildi'), ('lost', "Yo'qotilgan")], max_length=30, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('color', models.CharField(default='#3B82F6', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lead Status',
                'verbose_name_plural': 'Lead Statuses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SalesProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('max_leads_per_day', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='accounts.branch')),
                ('user', models.OneToOneField(limit_choices_to={'role__in': ['sales', 'sales_manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='sales_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Profile',
                'verbose_name_plural': 'Sales Profiles',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(choices=[('website', 'Veb-sayt'), ('social_media', 'Ijtimoiy tarmoq'), ('referral', 'Tavsiya'), ('walk_in', 'Tashrif'), ('phone', 'Telefon'), ('other', 'Boshqa')], default='other', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('trial_date', models.DateField(blank=True, null=True)),
                ('trial_time', models.TimeField(blank=True, null=True)),
                ('trial_result', models.CharField(blank=True, choices=[('attended', 'Keldi'), ('not_attended', 'Kelmadi'), ('accepted', 'Qabul qildi'), ('rejected', 'Rad etdi')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('expected_start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='accounts.branch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('sales', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['sales', 'sales_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.leadstatus')),
                ('trial_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_leads', to='courses.group')),
                ('trial_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_leads', to='courses.room')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('high', 'Yuqori'), ('medium', "O'rtacha"), ('low', 'Past')], default='medium', max_length=10)),
                ('is_overdue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='crm.lead')),
                ('sales', models.ForeignKey(limit_choices_to={'role__in': ['sales', 'sales_manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Follow Up',
                'verbose_name_plural': 'Follow Ups',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('sales', models.ForeignKey(limit_choices_to={'role__in': ['sales', 'sales_manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Schedule',
                'verbose_name_plural': 'Work Schedules',
                'ordering': ['sales', 'weekday'],
                'unique_together': {('sales', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='TrialLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('result', models.CharField(blank=True, choices=[('attended', 'Keldi'), ('not_attended', 'Kelmadi'), ('accepted', 'Qabul qildi'), ('rejected', 'Rad etdi')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_lessons', to='courses.group')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_lessons', to='crm.lead')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_lessons', to='courses.room')),
            ],
            options={
                'verbose_name': 'Trial Lesson',
                'verbose_name_plural': 'Trial Lessons',
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['lead', 'date'], name='crm_trialle_lead_id_b1b5e8_idx'), models.Index(fields=['group', 'date'], name='crm_trialle_group_i_800bd3_idx'), models.Index(fields=['date', 'start_time'], name='crm_trialle_date_d70e2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_contacts', models.IntegerField(default=0)),
                ('followup_completion_rate', models.FloatField(default=0.0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('overdue_followups', models.IntegerField(default=0)),
                ('enrolled_leads', models.IntegerField(default=0)),
                ('total_kpi_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales', models.ForeignKey(limit_choices_to={'role__in': ['sales', 'sales_manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='sales_kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales KPI',
                'verbose_name_plural': 'Sales KPIs',
                'ordering': ['-year', '-month', '-total_kpi_score'],
                'indexes': [models.Index(fields=['sales', 'year', 'month'], name='crm_saleskp_sales_i_3bfc67_idx'), models.Index(fields=['total_kpi_score', 'year', 'month'], name='crm_saleskp_total_k_ed24dc_idx')],
                'unique_together': {('sales', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('urgent', 'Shoshilinch'), ('high', 'Yuqori'), ('normal', 'Oddiy'), ('low', 'Past')], default='normal', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['sales', 'sales_manager']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(limit_choices_to={'role__in': ['admin', 'manager', 'sales_manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='crm_message_recipie_df98e6_idx'), models.Index(fields=['priority', 'created_at'], name='crm_message_priorit_b492a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'manager', 'sales_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('sales', models.ForeignKey(limit_choices_to={'role__in': ['sales', 'sales_manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave',
                'verbose_name_plural': 'Leaves',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sales', 'start_date', 'end_date'], name='crm_leave_sales_i_a08bf5_idx'), models.Index(fields=['status', 'start_date'], name='crm_leave_status_6d7dc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_history_changes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm.lead')),
                ('new_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_status_history', to='crm.leadstatus')),
                ('old_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_status_history', to='crm.leadstatus')),
            ],
            options={
                'verbose_name': 'Lead History',
                'verbose_name_plural': 'Lead Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', 'created_at'], name='crm_leadhis_lead_id_fd79ad_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'created_at'], name='crm_lead_status__3eb9eb_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['sales', 'status'], name='crm_lead_sales_i_0dd92d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['branch', 'status'], name='crm_lead_branch__5e65af_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['trial_date', 'trial_time'], name='crm_lead_trial_d_2ad4ce_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['sales', 'scheduled_at'], name='crm_followu_sales_i_534aef_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['is_completed', 'scheduled_at'], name='crm_followu_is_comp_f3c377_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['is_overdue', 'scheduled_at'], name='crm_followu_is_over_d72aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['lead', 'scheduled_at'], name='crm_followu_lead_id_25db60_idx'),
        ),
    ]
