# Generated by Django 4.2.7 on 2025-12-18 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_branch_options_alter_parentprofile_options_and_more'),
        ('courses', '0005_alter_course_options_alter_group_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('daily_contacts', models.IntegerField(default=0, verbose_name='Kunlik aloqalar')),
                ('daily_followups', models.IntegerField(default=0, verbose_name='Kunlik follow-uplar')),
                ('followup_completion_rate', models.FloatField(default=0.0, verbose_name='Bajarilish foizi')),
                ('trials_registered', models.IntegerField(default=0, verbose_name='Sinovga yozilganlar')),
                ('trials_to_sales', models.IntegerField(default=0, verbose_name='Sinovdan sotuv')),
                ('conversion_rate', models.FloatField(default=0.0, verbose_name='Konversiya foizi')),
                ('response_time_minutes', models.FloatField(default=0.0, verbose_name='Javob vaqti (daqiqa)')),
                ('overdue_count', models.IntegerField(default=0, verbose_name='Overdue soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Kunlik KPI',
                'verbose_name_plural': 'Kunlik KPIlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('offer_type', models.CharField(choices=[('discount', 'Chegirma'), ('bonus', 'Bonus'), ('package', 'Paket'), ('other', 'Boshqa')], default='discount', max_length=20, verbose_name='Taklif turi')),
                ('priority', models.CharField(choices=[('urgent', 'Shoshilinch'), ('high', 'Yuqori'), ('normal', 'Oddiy'), ('low', 'Past')], default='normal', max_length=10, verbose_name='Muhimlik')),
                ('channel', models.CharField(choices=[('all', 'Barchasi'), ('followup', 'Follow-up'), ('reactivation', 'Reaktivatsiya'), ('trial', 'Sinov'), ('general', 'Umumiy')], default='all', max_length=20, verbose_name='Kanal')),
                ('audience', models.CharField(choices=[('all', 'Barchasi'), ('new', 'Yangi lidlar'), ('lost', "Yo'qotilgan"), ('reactivation', 'Reaktivatsiya'), ('trial', 'Sinov')], default='all', max_length=20, verbose_name='Auditoriya')),
                ('valid_from', models.DateField(verbose_name='Boshlanish sanasi')),
                ('valid_until', models.DateField(verbose_name='Tugash sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Taklif',
                'verbose_name_plural': 'Takliflar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reactivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_since_lost', models.IntegerField(verbose_name="Yo'qotilganidan keyin kunlar")),
                ('reactivation_type', models.CharField(choices=[('7_days', '7 kun'), ('14_days', '14 kun'), ('30_days', '30 kun')], max_length=10, verbose_name='Reaktivatsiya turi')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('result', models.CharField(blank=True, choices=[('contacted', 'Aloqa qilindi'), ('interested', 'Qiziqdi'), ('no_response', "Javob yo'q")], max_length=20, null=True, verbose_name='Natija')),
            ],
            options={
                'verbose_name': 'Reaktivatsiya',
                'verbose_name_plural': 'Reaktivatsiyalar',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('priority', models.CharField(choices=[('urgent', 'Shoshilinch'), ('high', 'Yuqori'), ('normal', 'Oddiy'), ('low', 'Past')], default='normal', max_length=10, verbose_name='Muhimlik')),
                ('telegram_sent', models.BooleanField(default=False, verbose_name='Telegram orqali yuborildi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Sotuvchi xabari',
                'verbose_name_plural': 'Sotuvchi xabarlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesMessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name="O'qilgan vaqt")),
            ],
            options={
                'verbose_name': "Xabar o'qilishi",
                'verbose_name_plural': "Xabar o'qilishlari",
            },
        ),
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['due_date'], 'verbose_name': 'Follow-up', 'verbose_name_plural': 'Follow-uplar'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lid', 'verbose_name_plural': 'Lidlar'},
        ),
        migrations.AlterModelOptions(
            name='leadhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lid tarixi', 'verbose_name_plural': 'Lid tarixlari'},
        ),
        migrations.AlterModelOptions(
            name='leadstatus',
            options={'ordering': ['order'], 'verbose_name': 'Lid statusi', 'verbose_name_plural': 'Lid statuslari'},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-created_at'], 'verbose_name': "Ruxsat so'rovi", 'verbose_name_plural': "Ruxsat so'rovlari"},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'Xabar (eski)', 'verbose_name_plural': 'Xabarlar (eski)'},
        ),
        migrations.AlterModelOptions(
            name='saleskpi',
            options={'ordering': ['-year', '-month', '-total_kpi_score'], 'verbose_name': 'Oylik KPI', 'verbose_name_plural': 'Oylik KPIlar'},
        ),
        migrations.AlterModelOptions(
            name='salesprofile',
            options={'verbose_name': 'Sotuvchi profili', 'verbose_name_plural': 'Sotuvchi profillari'},
        ),
        migrations.AlterModelOptions(
            name='triallesson',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Sinov darsi', 'verbose_name_plural': 'Sinov darslari'},
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'ordering': ['sales', 'weekday'], 'verbose_name': 'Ish jadvali', 'verbose_name_plural': 'Ish jadvallari'},
        ),
        migrations.RemoveIndex(
            model_name='followup',
            name='crm_followu_sales_i_534aef_idx',
        ),
        migrations.RemoveIndex(
            model_name='followup',
            name='crm_followu_is_comp_f3c377_idx',
        ),
        migrations.RemoveIndex(
            model_name='followup',
            name='crm_followu_is_over_d72aa4_idx',
        ),
        migrations.RemoveIndex(
            model_name='followup',
            name='crm_followu_lead_id_25db60_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='crm_lead_sales_i_0dd92d_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='crm_message_recipie_df98e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='crm_message_priorit_b492a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='triallesson',
            name='crm_trialle_date_d70e2e_idx',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='description',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='title',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='expected_start_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='telegram_username',
        ),
        migrations.RemoveField(
            model_name='salesprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='triallesson',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='triallesson',
            name='start_time',
        ),
        migrations.AddField(
            model_name='followup',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Bajarildi'),
        ),
        migrations.AddField(
            model_name='followup',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bajarish vaqti'),
        ),
        migrations.AddField(
            model_name='followup',
            name='followup_sequence',
            field=models.IntegerField(default=1, verbose_name='Ketma-ketlik raqami'),
        ),
        migrations.AddField(
            model_name='followup',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Izohlar'),
        ),
        migrations.AddField(
            model_name='followup',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Eslatma yuborildi'),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_sales',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['sales', 'sales_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Biriktirilgan sotuvchi'),
        ),
        migrations.AddField(
            model_name='lead',
            name='enrolled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yozilgan vaqt'),
        ),
        migrations.AddField(
            model_name='lead',
            name='enrolled_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_leads', to='courses.group', verbose_name='Yozilgan guruh'),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='courses.course', verbose_name='Qiziqayotgan kurs'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Yo'qotilgan vaqt"),
        ),
        migrations.AddField(
            model_name='lead',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='lead',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Qo'shimcha telefon"),
        ),
        migrations.AddField(
            model_name='leave',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Rad etish sababi'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='absent_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ishda emaslik boshlanishi'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='absent_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Ishda emaslik sababi'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='absent_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ishda emaslik tugashi'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='is_absent',
            field=models.BooleanField(default=False, verbose_name='Ishda emas'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='is_active_sales',
            field=models.BooleanField(default=True, verbose_name='Faol sotuvchi'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='is_on_leave',
            field=models.BooleanField(default=False, verbose_name='Ruxsatda'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram chat ID'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='telegram_group_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram guruh ID'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='work_end_time',
            field=models.TimeField(default='18:00', verbose_name='Ish tugash vaqti'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='work_friday',
            field=models.BooleanField(default=True, verbose_name='Juma'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='work_monday',
            field=models.BooleanField(default=True, verbose_name='Dushanba'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='work_saturday',
            field=models.BooleanField(default=True, verbose_name='Shanba'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='work_start_time',
            field=models.TimeField(default='09:00', verbose_name='Ish boshlanish vaqti'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='work_sunday',
            field=models.BooleanField(default=False, verbose_name='Yakshanba'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='work_thursday',
            field=models.BooleanField(default=True, verbose_name='Payshanba'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='work_tuesday',
            field=models.BooleanField(default=True, verbose_name='Seshanba'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='work_wednesday',
            field=models.BooleanField(default=True, verbose_name='Chorshanba'),
        ),
        migrations.AddField(
            model_name='triallesson',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Eslatma yuborildi'),
        ),
        migrations.AddField(
            model_name='triallesson',
            name='sales_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Sotuvchi eslatmasi'),
        ),
        migrations.AddField(
            model_name='triallesson',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='is_overdue',
            field=models.BooleanField(default=False, verbose_name='Kechikkan'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='crm.lead', verbose_name='Lid'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='sales',
            field=models.ForeignKey(limit_choices_to={'role__in': ['sales', 'sales_manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Biriktirilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='accounts.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Izohlar'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('organic', 'Organik'), ('form', 'Veb-forma'), ('excel', 'Excel import'), ('google_sheets', 'Google Sheets'), ('referral', 'Tavsiya'), ('phone', 'Telefon'), ('walk_in', 'Tashrif'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Manba'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.leadstatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='trial_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sinov sanasi'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='trial_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_leads', to='courses.group', verbose_name='Sinov guruhi'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='trial_result',
            field=models.CharField(blank=True, choices=[('attended', 'Keldi'), ('not_attended', 'Kelmadi'), ('accepted', 'Qabul qildi'), ('rejected', 'Rad etdi')], max_length=20, null=True, verbose_name='Sinov natijasi'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='trial_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_leads', to='courses.room', verbose_name='Sinov xonasi'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='trial_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Sinov vaqti'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='leadhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_history_changes', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartiruvchi"),
        ),
        migrations.AlterField(
            model_name='leadhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='leadhistory',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm.lead', verbose_name='Lid'),
        ),
        migrations.AlterField(
            model_name='leadhistory',
            name='new_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_status_history', to='crm.leadstatus', verbose_name='Yangi status'),
        ),
        migrations.AlterField(
            model_name='leadhistory',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Izohlar'),
        ),
        migrations.AlterField(
            model_name='leadhistory',
            name='old_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_status_history', to='crm.leadstatus', verbose_name='Eski status'),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='code',
            field=models.CharField(choices=[('new', 'Yangi'), ('contacted', 'Aloqa qilindi'), ('interested', 'Qiziqmoqda'), ('trial_registered', 'Sinovga yozildi'), ('trial_attended', 'Sinovga keldi'), ('trial_not_attended', 'Sinovga kelmadi'), ('offer_sent', 'Sotuv taklifi'), ('enrolled', 'Kursga yozildi'), ('lost', "Yo'qotilgan"), ('reactivation', 'Qayta aloqa')], max_length=30, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=20, verbose_name='Rang'),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'manager', 'sales_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.TextField(verbose_name='Sabab'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='sales',
            field=models.ForeignKey(limit_choices_to={'role__in': ['sales', 'sales_manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='saleskpi',
            name='average_response_time',
            field=models.FloatField(default=0.0, verbose_name="O'rtacha javob vaqti"),
        ),
        migrations.AlterField(
            model_name='saleskpi',
            name='conversion_rate',
            field=models.FloatField(default=0.0, verbose_name='Konversiya foizi'),
        ),
        migrations.AlterField(
            model_name='saleskpi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='saleskpi',
            name='enrolled_leads',
            field=models.IntegerField(default=0, verbose_name='Yozilgan lidlar'),
        ),
        migrations.AlterField(
            model_name='saleskpi',
            name='followup_completion_rate',
            field=models.FloatField(default=0.0, verbose_name='Follow-up bajarilishi'),
        ),
        migrations.AlterField(
            model_name='saleskpi',
            name='month',
            field=models.IntegerField(verbose_name='Oy'),
        ),
        migrations.AlterField(
            model_name='saleskpi',
            name='overdue_followups',
            field=models.IntegerField(default=0, verbose_name='Overdue follow-uplar'),
        ),
        migrations.AlterField(
            model_name='saleskpi',
            name='sales',
            field=models.ForeignKey(limit_choices_to={'role__in': ['sales', 'sales_manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='sales_kpis', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi'),
        ),
        migrations.AlterField(
            model_name='saleskpi',
            name='total_contacts',
            field=models.IntegerField(default=0, verbose_name='Jami aloqalar'),
        ),
        migrations.AlterField(
            model_name='saleskpi',
            name='total_kpi_score',
            field=models.FloatField(default=0.0, verbose_name='Umumiy KPI ball'),
        ),
        migrations.AlterField(
            model_name='saleskpi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='saleskpi',
            name='year',
            field=models.IntegerField(verbose_name='Yil'),
        ),
        migrations.AlterField(
            model_name='salesprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='accounts.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='salesprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='salesprofile',
            name='max_leads_per_day',
            field=models.IntegerField(default=10, verbose_name='Kunlik maksimal lidlar'),
        ),
        migrations.AlterField(
            model_name='salesprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='salesprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role__in': ['sales', 'sales_manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='sales_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_lessons', to='courses.group', verbose_name='Guruh'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_lessons', to='crm.lead', verbose_name='Lid'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Izohlar'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='result',
            field=models.CharField(blank=True, choices=[('attended', 'Keldi'), ('not_attended', 'Kelmadi'), ('accepted', 'Qabul qildi'), ('rejected', 'Rad etdi')], max_length=20, null=True, verbose_name='Natija'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_lessons', to='courses.room', verbose_name='Xona'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='end_time',
            field=models.TimeField(verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='sales',
            field=models.ForeignKey(limit_choices_to={'role__in': ['sales', 'sales_manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='start_time',
            field=models.TimeField(verbose_name='Boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], verbose_name='Hafta kuni'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['sales', 'due_date'], name='crm_followu_sales_i_669bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['completed', 'due_date'], name='crm_followu_complet_30b08c_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['is_overdue', 'due_date'], name='crm_followu_is_over_4a816c_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['lead', 'due_date'], name='crm_followu_lead_id_e70e78_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_sales', 'status'], name='crm_lead_assigne_0bca9b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='crm_lead_phone_8180e8_idx'),
        ),
        migrations.AddIndex(
            model_name='triallesson',
            index=models.Index(fields=['date', 'time'], name='crm_trialle_date_971a9d_idx'),
        ),
        migrations.AddField(
            model_name='salesmessageread',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='crm.salesmessage', verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='salesmessageread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reads', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='salesmessage',
            name='recipients',
            field=models.ManyToManyField(limit_choices_to={'role__in': ['sales', 'sales_manager']}, related_name='received_sales_messages', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchilar'),
        ),
        migrations.AddField(
            model_name='salesmessage',
            name='sender',
            field=models.ForeignKey(limit_choices_to={'role__in': ['admin', 'manager', 'sales_manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_sales_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi'),
        ),
        migrations.AddField(
            model_name='reactivation',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactivations', to='crm.lead', verbose_name='Lid'),
        ),
        migrations.AddField(
            model_name='offer',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='courses.course', verbose_name='Kurs'),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi'),
        ),
        migrations.AddField(
            model_name='dailykpi',
            name='sales',
            field=models.ForeignKey(limit_choices_to={'role__in': ['sales', 'sales_manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_kpis', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi'),
        ),
        migrations.AlterUniqueTogether(
            name='salesmessageread',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='reactivation',
            index=models.Index(fields=['lead', 'reactivation_type'], name='crm_reactiv_lead_id_4d1fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='crm_offer_is_acti_322d89_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['offer_type', 'is_active'], name='crm_offer_offer_t_9b4895_idx'),
        ),
        migrations.AddIndex(
            model_name='dailykpi',
            index=models.Index(fields=['sales', 'date'], name='crm_dailykp_sales_i_b736f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailykpi',
            unique_together={('sales', 'date')},
        ),
    ]
