# Generated by Django 4.2.7 on 2025-12-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_dailykpi_offer_reactivation_salesmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triallesson',
            name='reminder_2_hours_sent',
            field=models.BooleanField(default=False, verbose_name='2 soat oldin eslatma yuborildi'),
        ),
        migrations.AddField(
            model_name='triallesson',
            name='reminder_8_10_sent',
            field=models.BooleanField(default=False, verbose_name='8-10 soat oldin eslatma yuborildi'),
        ),
    ]
