# Generated by Django 4.2.7 on 2025-12-27 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0003_add_trial_reminder_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_student',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_lead', to=settings.AUTH_USER_MODEL, verbose_name='Studentga aylantirilgan'),
        ),
    ]
