# Generated by Django 5.0.1 on 2025-12-15 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_accounts_us_role_2b136f_idx_and_more'),
        ('attendance', '0002_attendance_attendance__student_ce9d17_idx_and_more'),
        ('courses', '0003_course_courses_cou_is_acti_63c274_idx_and_more'),
        ('exams', '0002_exam_exams_exam_date_adbaa1_idx_and_more'),
        ('homework', '0002_homework_homework_ho_student_ade818_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('badge_type', models.CharField(choices=[('top_student', 'Top Student'), ('perfect_attendance', 'Perfect Attendance'), ('fast_learner', 'Fast Learner'), ('homework_master', 'Homework Master'), ('champion_month', 'Champion of the Month'), ('exam_champion', 'Exam Champion'), ('consistent_learner', 'Consistent Learner')], max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='🏆', max_length=100)),
                ('points_required', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['points_required'],
            },
        ),
        migrations.CreateModel(
            name='BranchRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('total_points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='accounts.branch')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='branch_rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch Ranking',
                'verbose_name_plural': 'Branch Rankings',
                'ordering': ['branch', 'rank'],
                'indexes': [models.Index(fields=['branch', 'rank'], name='gamificatio_branch__185ca1_idx'), models.Index(fields=['student', 'branch'], name='gamificatio_student_2c7003_idx')],
                'unique_together': {('branch', 'student')},
            },
        ),
        migrations.CreateModel(
            name='GroupRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('total_points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='courses.group')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='group_rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Ranking',
                'verbose_name_plural': 'Group Rankings',
                'ordering': ['group', 'rank'],
                'indexes': [models.Index(fields=['group', 'rank'], name='gamificatio_group_i_060807_idx'), models.Index(fields=['student', 'group'], name='gamificatio_student_5252e4_idx')],
                'unique_together': {('group', 'student')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_type', models.CharField(choices=[('top_10', 'Top 10'), ('top_25', 'Top 25'), ('top_50', 'Top 50'), ('top_100', 'Top 100')], max_length=10)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('total_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Ranking',
                'verbose_name_plural': 'Monthly Rankings',
                'ordering': ['year', 'month', 'ranking_type', 'rank'],
                'indexes': [models.Index(fields=['year', 'month', 'ranking_type', 'rank'], name='gamificatio_year_072ee2_idx'), models.Index(fields=['student', 'year', 'month'], name='gamificatio_student_403c6e_idx')],
                'unique_together': {('student', 'ranking_type', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='OverallRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('total_points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='overall_ranking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overall Ranking',
                'verbose_name_plural': 'Overall Rankings',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['rank'], name='gamificatio_rank_215f81_idx'), models.Index(fields=['total_points'], name='gamificatio_total_p_c899f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('point_type', models.CharField(choices=[('attendance_present', 'Darsga qatnashish'), ('homework_on_time', 'Uy vazifani vaqtida topshirish'), ('homework_late', 'Uy vazifani kech topshirish'), ('attendance_absent', 'Darsni qoldirish'), ('exam_high_score', 'Imtihondan yuqori ball'), ('badge_earned', 'Badge olish'), ('manual', "Qo'lda qo'shish")], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='attendance.attendance')),
                ('exam_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='exams.examresult')),
                ('homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='homework.homework')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point Transaction',
                'verbose_name_plural': 'Point Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'created_at'], name='gamificatio_student_81703a_idx'), models.Index(fields=['point_type', 'created_at'], name='gamificatio_point_t_ab8e24_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_badges', to='gamification.badge')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_badges', to='courses.group')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Badge',
                'verbose_name_plural': 'Student Badges',
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['student', 'earned_at'], name='gamificatio_student_72a7e0_idx'), models.Index(fields=['badge', 'earned_at'], name='gamificatio_badge_i_174101_idx')],
                'unique_together': {('student', 'badge', 'group')},
            },
        ),
        migrations.CreateModel(
            name='StudentPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_points', to='courses.group')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Points',
                'verbose_name_plural': 'Student Points',
                'ordering': ['-total_points'],
                'indexes': [models.Index(fields=['group', 'total_points'], name='gamificatio_group_i_d2bdd2_idx'), models.Index(fields=['student', 'group'], name='gamificatio_student_03c570_idx')],
                'unique_together': {('student', 'group')},
            },
        ),
    ]
